x-app: &default-app
  # restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  env_file:
    - .env
  # healthcheck:
  #   test: ["CMD", "curl", "-f", "http://localhost:5000"]
  #   interval: "60s"
  #   timeout: "3s"
  #   start_period: "5s"
  #   retries: 3

services:
  backend:
    <<: *default-app
    build:
      context: "./backend/"
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    <<: *default-app
    build:
      context: "./frontend/"
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
